name: Node Release

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

on:
  push:
    tags:
      - tokenizers-node-v*
    branches:
      - node-workflow

jobs:
  node_pre_gyp:
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2019-11-01
          override: true

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./bindings/node
        run: npm ci

      - working-directory: ./bindings/node
        run: node publish.js

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Upload tarball
        # if: startsWith(matrix.os, 'windows')
        working-directory: ./bindings/node
        shell: bash
        run: |
          pip install awscli
          aws s3 sync --exact-timestamps --exclude "*" --include "*.tar.gz" --acl public-read ./bin-package "s3://tokenizers-releases/node/$(node -p -e 'require("./package.json").version')-test"
